//! `doc-linter gen-docs [--check]` — regenerates the reference docs whose
//! source of truth is code, so they can't drift from it:
//!
//! - `docs/error-codes.md` from `validator::code_table`;
//! - `docs/reference/cli.md` from the clap `Command` tree;
//! - `docs/reference/mcp.md` from the MCP `tools/list` catalog;
//! - `docs/reference/config.md` from the `LintConfig` structs: keys and
//!   descriptions from their `///` doc comments, defaults from what serde
//!   yields for an empty `.doc-lint.toml`.
//!
//! `--check` writes nothing and fails when a committed file differs; the
//! `generated_docs_are_current` test runs the same comparison in CI.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;
use std::process::ExitCode;

use anyhow::{Context, Result};
use clap::CommandFactory;
use serde_json::Value;

use doc_linter::config::LintConfig;
use doc_linter::validator::code_table;

/// Every generated doc as `(repo-relative path, content)`.
pub(crate) fn outputs() -> Result<Vec<(&'static str, String)>> {
    Ok(vec![
        ("docs/error-codes.md", code_table::render_markdown()),
        ("docs/reference/cli.md", render_cli()),
        ("docs/reference/mcp.md", render_mcp()),
        ("docs/reference/config.md", render_config()?),
    ])
}

/// Write every generated doc under `root`, or with `check` report the
/// stale ones and fail.
pub(crate) fn run(root: &Path, check: bool) -> Result<ExitCode> {
    let mut stale = Vec::new();
    for (rel, content) in outputs()? {
        let path = root.join(rel);
        let current = std::fs::read_to_string(&path).unwrap_or_default();
        if current == content {
            continue;
        }
        if check {
            stale.push(rel);
        } else {
            if let Some(dir) = path.parent() {
                std::fs::create_dir_all(dir)?;
            }
            std::fs::write(&path, content).with_context(|| format!("write {rel}"))?;
            eprintln!("doc-linter gen-docs: wrote {rel}");
        }
    }
    if stale.is_empty() {
        return Ok(ExitCode::SUCCESS);
    }
    eprintln!(
        "doc-linter gen-docs --check: stale: {} — run `doc-linter gen-docs`",
        stale.join(", ")
    );
    Ok(ExitCode::FAILURE)
}

fn frontmatter(id: &str, title: &str, summary: &str, covers: &str) -> String {
    format!(
        "---\n\
         id: {id}\n\
         role: doc\n\
         kind: reference\n\
         lifecycle: stable\n\
         covers: [{covers}]\n\
         title: {title}\n\
         summary: \"{summary}\"\n\
         status: stable\n\
         updated: 2026-10-01\n\
         tags: [reference, generated]\n\
         ---\n\n\
         <!-- Generated by `doc-linter gen-docs`; edit the source, not this file. -->\n\n\
         # {title}\n\n"
    )
}

/// Source prose made safe to embed in `docs/reference/`:
/// - a `[[id]]` wikilink in a doc comment points into the author's vault,
///   which may not be this repo's graph, so it becomes `` `id` ``;
/// - a `` `path` `` naming a file in this repo becomes a link to it, so
///   the reference can't point at a file that moved.
fn plain(text: &str) -> String {
    static RES: std::sync::OnceLock<(regex::Regex, regex::Regex)> = std::sync::OnceLock::new();
    #[allow(
        clippy::unwrap_used,
        reason = "literal regexes; compile is infallible at runtime"
    )]
    let (wikilink, path) = RES.get_or_init(|| {
        (
            regex::Regex::new(r"\[\[([^\]]+)\]\]").unwrap(),
            regex::Regex::new(r"`([A-Za-z0-9_.-]+(?:/[A-Za-z0-9_.-]+)+)`").unwrap(),
        )
    });
    let text = wikilink.replace_all(text, "`$1`");
    let repo = Path::new(env!("CARGO_MANIFEST_DIR"));
    path.replace_all(&text, |c: &regex::Captures<'_>| {
        if repo.join(&c[1]).is_file() {
            format!("[`{0}`](../../{0})", &c[1])
        } else {
            c[0].to_string()
        }
    })
    .into_owned()
}

/// One table cell: single line, pipes escaped, and `<…>` outside code
/// spans escaped so it isn't read as an HTML tag.
fn cell(text: &str) -> String {
    plain(text)
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .split('`')
        .enumerate()
        .map(|(i, part)| {
            if i % 2 == 0 {
                part.replace('<', "&lt;").replace('>', "&gt;")
            } else {
                part.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("`")
        .replace('|', "\\|")
}

// ---------------------------------------------------------------- CLI

fn render_cli() -> String {
    let mut cmd = crate::Cli::command();
    cmd.build();
    let mut s = frontmatter(
        "reference-cli",
        "CLI reference",
        "Every doc-linter subcommand and flag, generated from the clap definition.",
        "doc-graph, endpoint",
    );
    s.push_str(
        "Quick start: [[quickstart-cli]]. Generated from the clap definition in \
         [`src/main.rs`](../../src/main.rs) and [`src/cmd/mod.rs`](../../src/cmd/mod.rs); \
         `doc-linter <command> --help` prints the same text.\n\n",
    );
    s.push_str("## Global options\n\nAccepted by every subcommand.\n\n");
    let globals: Vec<&clap::Arg> = cmd
        .get_arguments()
        .filter(|a| a.is_global_set() && !is_builtin(a))
        .collect();
    push_arg_table(&mut s, &globals);
    for sub in cmd.get_subcommands() {
        push_command(&mut s, sub, "doc-linter");
    }
    s
}

fn is_builtin(arg: &clap::Arg) -> bool {
    matches!(arg.get_id().as_str(), "help" | "version")
}

fn push_command(s: &mut String, cmd: &clap::Command, parent: &str) {
    if cmd.is_hide_set() || cmd.get_name() == "help" {
        return;
    }
    let path = format!("{parent} {}", cmd.get_name());
    let _ = write!(s, "## `{path}`\n\n");
    if let Some(about) = cmd.get_long_about().or_else(|| cmd.get_about()) {
        let _ = write!(s, "{}\n\n", plain(about.to_string().trim()));
    }
    let args: Vec<&clap::Arg> = cmd
        .get_arguments()
        .filter(|a| !a.is_global_set() && !a.is_hide_set() && !is_builtin(a))
        .collect();
    if !args.is_empty() {
        push_arg_table(s, &args);
    }
    for sub in cmd.get_subcommands() {
        push_command(s, sub, &path);
    }
}

fn push_arg_table(s: &mut String, args: &[&clap::Arg]) {
    s.push_str("| Argument | Default | Description |\n|---|---|---|\n");
    for arg in args {
        let value = arg
            .get_value_names()
            .and_then(|v| v.first())
            .map_or_else(|| arg.get_id().as_str().to_uppercase(), ToString::to_string);
        let takes_value = arg.get_num_args().is_some_and(|n| n.takes_values());
        let name = match arg.get_long() {
            None => format!("`<{value}>`"),
            Some(long) if takes_value => format!("`--{long} <{value}>`"),
            Some(long) => format!("`--{long}`"),
        };
        let defaults: Vec<String> = arg
            .get_default_values()
            .iter()
            .map(|v| v.to_string_lossy().into_owned())
            .collect();
        let default = if defaults.is_empty() || !takes_value {
            String::new()
        } else {
            format!("`{}`", defaults.join(", "))
        };
        let mut help = arg
            .get_long_help()
            .or_else(|| arg.get_help())
            .map(ToString::to_string)
            .unwrap_or_default();
        let values: Vec<String> = arg
            .get_possible_values()
            .iter()
            .filter(|v| !v.is_hide_set())
            .map(|v| format!("`{}`", v.get_name()))
            .collect();
        if takes_value && !values.is_empty() {
            if !help.is_empty() && !help.ends_with('.') {
                help.push('.');
            }
            let _ = write!(help, " Values: {}.", values.join(", "));
        }
        let _ = writeln!(s, "| {name} | {default} | {} |", cell(&help));
    }
    s.push('\n');
}

// ---------------------------------------------------------------- MCP

fn render_mcp() -> String {
    let list = super::mcp::tools_list();
    let mut s = frontmatter(
        "reference-mcp",
        "MCP tool reference",
        "Every tool the doc-linter MCP server advertises, generated from its tools/list catalog.",
        "doc-graph, endpoint",
    );
    s.push_str(
        "Quick start: [[quickstart-mcp]]. Generated from the `tools/list` catalog served by \
         `doc-linter mcp` ([`src/cmd/mcp.rs`](../../src/cmd/mcp.rs)). On a docs-only graph the server hides the \
         code-only tools from `tools/list`; they stay callable.\n\n",
    );
    for tool in list["tools"].as_array().into_iter().flatten() {
        let name = tool["name"].as_str().unwrap_or_default();
        let _ = write!(
            s,
            "## `{name}`\n\n{}\n\n",
            cell(tool["description"].as_str().unwrap_or_default()).replace("\\|", "|")
        );
        let schema = &tool["inputSchema"];
        let required: Vec<&str> = schema["required"]
            .as_array()
            .into_iter()
            .flatten()
            .filter_map(Value::as_str)
            .collect();
        let Some(props) = schema["properties"].as_object().filter(|p| !p.is_empty()) else {
            s.push_str("No parameters.\n\n");
            continue;
        };
        s.push_str("| Parameter | Type | Required | Description |\n|---|---|---|---|\n");
        for (param, spec) in props {
            let ty = spec["type"].as_str().unwrap_or("any");
            let mut desc = spec["description"].as_str().unwrap_or_default().to_string();
            if let Some(values) = spec["enum"].as_array() {
                let values: Vec<String> = values.iter().map(|v| format!("`{v}`")).collect();
                let _ = write!(desc, " Values: {}.", values.join(", "));
            }
            let req = if required.contains(&param.as_str()) {
                "yes"
            } else {
                ""
            };
            let _ = writeln!(s, "| `{param}` | {ty} | {req} | {} |", cell(&desc));
        }
        s.push('\n');
    }
    s
}

// ---------------------------------------------------------------- config

/// The config structs whose fields are `.doc-lint.toml` keys: source,
/// struct name, key prefix, section heading. Flattened sub-structs share
/// the top level; `cluster_lint` is its own table.
const CONFIG_SOURCES: &[(&str, &str, &str, &str)] = &[
    (
        include_str!("../config/mod.rs"),
        "LintConfig",
        "",
        "Corpus and general",
    ),
    (
        include_str!("../config/lint_rules.rs"),
        "LintRules",
        "",
        "Frontmatter rules",
    ),
    (
        include_str!("../config/vale.rs"),
        "ValeConfig",
        "",
        "Vale and vocabulary",
    ),
    (
        include_str!("../config/coverage.rs"),
        "CoverageConfig",
        "",
        "Code coverage",
    ),
    (
        include_str!("../config/layout.rs"),
        "LayoutConfig",
        "",
        "Layout",
    ),
    (
        include_str!("../config/ontology.rs"),
        "OntologyConfig",
        "",
        "Ontology",
    ),
    (
        include_str!("../config/cluster_lint.rs"),
        "ClusterLintConfig",
        "cluster_lint.",
        "`[cluster_lint]` table",
    ),
];

/// One `.doc-lint.toml` key parsed from a config struct.
#[derive(Debug)]
struct ConfigField {
    key: String,
    ty: String,
    doc: String,
}

/// Fields of `struct_name` in `src`, from `pub name: Type,` lines and the
/// `///` / `#[serde(...)]` lines above them. Skips `skip` (runtime-only)
/// and `flatten` (sub-struct) fields; honours `rename`.
fn parse_struct_fields(src: &str, struct_name: &str) -> Vec<ConfigField> {
    let mut out = Vec::new();
    let mut inside = false;
    let mut doc: Vec<String> = Vec::new();
    let mut attrs = String::new();
    for line in src.lines() {
        let t = line.trim();
        if !inside {
            inside = t == format!("pub struct {struct_name} {{");
            continue;
        }
        if line.starts_with('}') {
            break;
        }
        if let Some(d) = t.strip_prefix("///") {
            doc.push(d.trim().to_string());
        } else if t.starts_with("#[") {
            attrs.push_str(t);
        } else if let Some((name, ty)) = t.strip_prefix("pub ").and_then(|r| r.split_once(':')) {
            let skipped = attrs
                .split(|c: char| !(c.is_alphanumeric() || c == '_'))
                .any(|w| w == "skip" || w == "flatten");
            if !skipped {
                let key = attrs
                    .split("rename = \"")
                    .nth(1)
                    .and_then(|r| r.split('"').next())
                    .unwrap_or(name)
                    .to_string();
                out.push(ConfigField {
                    key,
                    ty: ty.trim().trim_end_matches(',').to_string(),
                    doc: doc.join(" "),
                });
            }
            doc.clear();
            attrs.clear();
        } else if t.is_empty() {
            doc.clear();
            attrs.clear();
        }
    }
    out
}

/// What serde fills in for an empty `.doc-lint.toml`, flattened to
/// `key -> TOML value` (`cluster_lint.*` for the nested table).
fn config_defaults() -> Result<BTreeMap<String, toml::Value>> {
    let cfg: LintConfig = toml::from_str("").context("deserialize empty .doc-lint.toml")?;
    let toml::Value::Table(table) = toml::Value::try_from(&cfg)? else {
        anyhow::bail!("LintConfig did not serialize to a table");
    };
    let mut out = BTreeMap::new();
    for (k, v) in table {
        match (k.as_str(), v) {
            ("cluster_lint", toml::Value::Table(sub)) => {
                for (sk, sv) in sub {
                    out.insert(format!("cluster_lint.{sk}"), sv);
                }
            }
            (_, v) => {
                out.insert(k, v);
            }
        }
    }
    Ok(out)
}

fn render_default(v: Option<&toml::Value>) -> String {
    let Some(v) = v else {
        return "unset".to_string();
    };
    let text = v.to_string();
    // Long built-in lists (exempt globs, function-exempt regexes) would
    // swamp the table; their full text is in the source.
    if text.len() > 400 {
        let n = v.as_array().map_or(0, Vec::len);
        return format!("{n} built-in entries");
    }
    format!("`{}`", text.replace('|', "\\|"))
}

/// Every documented config key, in source order, with its section.
fn config_fields() -> Vec<(&'static str, ConfigField)> {
    CONFIG_SOURCES
        .iter()
        .flat_map(|(src, name, prefix, section)| {
            parse_struct_fields(src, name)
                .into_iter()
                .map(move |mut f| {
                    f.key = format!("{prefix}{}", f.key);
                    (*section, f)
                })
        })
        // `_`-prefixed keys are legacy aliases; `cluster_lint` is the
        // table whose keys are listed under their own heading.
        .filter(|(_, f)| !f.key.starts_with('_') && f.key != "cluster_lint")
        .collect()
}

fn render_config() -> Result<String> {
    let defaults = config_defaults()?;
    let mut s = frontmatter(
        "reference-config",
        "Configuration reference",
        "Every .doc-lint.toml key with its type, default and meaning, generated from the config structs.",
        "doc-graph",
    );
    s.push_str(
        "Quick start: [[quickstart-config]]. Generated from the config structs in \
         [`src/config/`](../../src/config/mod.rs): each key's description is its doc comment, and its default is what \
         `doc-linter` uses when the key is absent. Keys sit at the top level of \
         `.doc-lint.toml` unless shown as `table.key`.\n",
    );
    let mut section = "";
    for (sec, f) in config_fields() {
        if sec != section {
            section = sec;
            let _ = write!(
                s,
                "\n## {sec}\n\n| Key | Type | Default | Description |\n|---|---|---|---|\n"
            );
        }
        let _ = writeln!(
            s,
            "| `{}` | `{}` | {} | {} |",
            f.key,
            f.ty,
            render_default(defaults.get(&f.key)),
            cell(&f.doc)
        );
    }
    Ok(s)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The committed generated docs match the code. Regenerate with
    /// `doc-linter gen-docs`.
    #[test]
    fn generated_docs_are_current() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        let stale: Vec<&str> = outputs()
            .unwrap()
            .into_iter()
            .filter(|(rel, content)| {
                std::fs::read_to_string(root.join(rel)).unwrap_or_default() != *content
            })
            .map(|(rel, _)| rel)
            .collect();
        assert!(
            stale.is_empty(),
            "stale: {stale:?} — run `doc-linter gen-docs`"
        );
    }

    /// Every key serde reads is documented and found by the parser, so
    /// a new config field can't land without a reference entry.
    #[test]
    fn every_config_key_is_documented() {
        let fields = config_fields();
        let undocumented: Vec<&str> = fields
            .iter()
            .filter(|(_, f)| f.doc.is_empty())
            .map(|(_, f)| f.key.as_str())
            .collect();
        assert!(
            undocumented.is_empty(),
            "add a /// doc comment: {undocumented:?}"
        );
        let parsed: Vec<&str> = fields.iter().map(|(_, f)| f.key.as_str()).collect();
        let missing: Vec<String> = config_defaults()
            .unwrap()
            .into_keys()
            .filter(|k| !k.starts_with('_') && !parsed.contains(&k.as_str()))
            .filter(|k| k != "cluster_lint")
            .collect();
        assert!(missing.is_empty(), "keys the parser missed: {missing:?}");
    }
}
