//! `doc-linter migrate-anchor-required` subcommand. Roadmap-48 Rule A —
//! snapshots the doc-graph's current dark-public-function surface as
//! a grandfather list for the Force-Growth lint gate.

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use anyhow::{Context, Result};

use doc_linter::config::LintConfig;
use doc_linter::graph_read::ReadGraph;
use doc_linter::scaffold;

/// Opens (or builds, if cold) the SQLite graph, queries every dark
/// public function in the corpus regardless of `anchor_required_in`
/// — we want the whole grandfathered surface, not just the
/// already-enforced subset — and writes the bare function names to
/// `coverage_anchor_exempt_file`. The on-disk format is one bare
/// name per line, sorted + deduplicated, with a leading header
/// comment block explaining the file's purpose and refresh story.
///
/// Idempotent by construction: re-running overwrites the file with
/// the current snapshot. A function that gained an entity link
/// since the previous snapshot drops out of the list naturally.
/// The file is NOT auto-committed; authors review it as part of
/// the PR that flips `require_anchor_per_pubapi` to default-true.
/// @endpoint CLI migrate-anchor-required
pub(crate) fn run(root: &Path, config: &LintConfig, _all_files: &[PathBuf]) -> Result<ExitCode> {
    let db = ReadGraph::open(root)?;

    // Query the full dark-function surface across every crate in
    // the graph. The per-crate `list_dark_public_functions` helper
    // bails on an empty `anchor_required_in` (its caller is the
    // Phase-3 lint, which legitimately wants "no enforcement when
    // the list is empty"); the migrate path needs the inverse —
    // every dark fn regardless of which crate authored it — so we
    // call the sibling [`store::list_all_dark_public_functions`].
    let dark = db.list_all_dark_public_functions(config)?;

    // Bare names, sorted + deduped.
    let mut names: Vec<String> = Vec::new();
    for row in &dark {
        if let Some(bare) = scaffold::bare_fn_name(&row.symbol) {
            names.push(bare);
        }
    }
    names.sort();
    names.dedup();

    let target = if config.coverage.coverage_anchor_exempt_file.is_absolute() {
        config.coverage.coverage_anchor_exempt_file.clone()
    } else {
        root.join(&config.coverage.coverage_anchor_exempt_file)
    };
    if let Some(parent) = target.parent() {
        std::fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    }

    let today = chrono::Local::now().date_naive();
    let mut body = String::new();
    body.push_str(&format!(
        "# Auto-generated by `doc-linter migrate-anchor-required` on {today}.\n"
    ));
    body.push_str(
        "# One bare function name per line. These functions were dark when\n\
         # `require_anchor_per_pubapi` flipped to default-true; new public\n\
         # functions added after this snapshot must reference an ontology\n\
         # entity. To remove an entry, link the function to an entity in\n\
         # its doc-comment, then re-run `migrate-anchor-required` to refresh.\n",
    );
    for name in &names {
        body.push_str(name);
        body.push('\n');
    }
    std::fs::write(&target, &body).with_context(|| format!("write {}", target.display()))?;

    eprintln!(
        "doc-linter migrate-anchor-required: wrote {} bare-name(s) to {}",
        names.len(),
        target.display()
    );
    Ok(ExitCode::SUCCESS)
}
