//! Saved queries on the SQLite store (docs/design/saved-query-port.md).
//!
//! Built-in SQL is the embedded `saved_sql/*.sql` table generated by
//! `build.rs`; a runtime TOML query supplies `sql = "..."` next to (or
//! instead of) `sql`. Catalog, params and defaults are the the store ones.

use std::collections::HashMap;
use std::path::Path;

use anyhow::{bail, Context, Result};
use rusqlite::types::ValueRef;

use super::SqliteDb;
use crate::store::query::saved::{fill_params, resolve_query};

include!(concat!(env!("OUT_DIR"), "/saved_sql_table.rs"));

/// Embedded SQL for a built-in catalog entry.
pub fn builtin_sql(name: &str) -> Option<&'static str> {
    SAVED_SQL.iter().find(|(n, _)| *n == name).map(|(_, s)| *s)
}

/// Run the saved query `name` (built-in or runtime) with `--param`
/// values; same result shape as the the store runner.
pub fn run_saved_query_with_root(
    db: &SqliteDb,
    root: Option<&Path>,
    name: &str,
    params: &HashMap<String, String>,
) -> Result<serde_json::Value> {
    let q = resolve_query(root, name)?;
    let params = fill_params(&q, name, params)?;
    let sql: String = match (&q.sql, q.origin.as_str()) {
        (Some(s), _) => s.clone(),
        // A corpus-local override that only has `sql` must not silently
        // fall back to the built-in of the same name.
        (None, "corpus-local") => bail!("query saved {name}: runtime query has no `sql` form"),
        (None, _) => builtin_sql(name)
            .with_context(|| format!("query saved {name}: no SQL translation"))?
            .to_string(),
    };
    run_sql(db, &sql, &params)
}

/// Prepare `sql`, bind each `--param` the statement mentions as text
/// (extras are ignored, as in the SQL substitution) and return
/// `{columns,row_count,rows}`.
pub fn run_sql(
    db: &SqliteDb,
    sql: &str,
    params: &HashMap<String, String>,
) -> Result<serde_json::Value> {
    let bound: Vec<(&str, crate::store::Value)> = params
        .iter()
        .map(|(k, v)| (k.as_str(), crate::store::Value::Str(v.clone())))
        .collect();
    run_sql_values(db, sql, &bound, false)
}

/// Read-only raw SQL (`query sql`, MCP `sql`): the statement must be a
/// single `SELECT` / `WITH` that SQLite itself reports as read-only
/// (`sqlite3_stmt_readonly`), so a `WITH ... DELETE` is refused too.
/// Parameters bind by `$name`; names the statement does not mention are
/// ignored. Result shape is the SQL one: `{columns,row_count,rows}`.
pub fn run_readonly_sql(
    db: &SqliteDb,
    sql: &str,
    params: &[(&str, crate::store::Value)],
) -> Result<serde_json::Value> {
    let mut rest = sql.trim_start();
    // Skip leading comments so `-- note\nSELECT ..` is accepted.
    loop {
        if let Some(r) = rest.strip_prefix("--") {
            rest = r.split_once('\n').map_or("", |(_, t)| t).trim_start();
        } else if let Some(r) = rest.strip_prefix("/*") {
            rest = r.split_once("*/").map_or("", |(_, t)| t).trim_start();
        } else {
            break;
        }
    }
    let word: String = rest
        .chars()
        .take_while(char::is_ascii_alphabetic)
        .collect::<String>()
        .to_ascii_lowercase();
    if word != "select" && word != "with" {
        bail!("sql is read-only: the statement must start with SELECT or WITH");
    }
    if has_second_statement(sql) {
        bail!("sql is read-only: pass a single statement (found text after `;`)");
    }
    run_sql_values(db, sql, params, true)
}

/// True when anything but whitespace and comments follows a `;` that is
/// outside string literals, quoted identifiers and comments. (SQLite's
/// `prepare` compiles only the first statement and hands back the tail, so
/// the tail has to be checked here.)
fn has_second_statement(sql: &str) -> bool {
    let b = sql.as_bytes();
    let (mut i, mut ended) = (0, false);
    while i < b.len() {
        match b[i] {
            q @ (b'\'' | b'"' | b'`') if !ended => {
                i += 1;
                while i < b.len() && b[i] != q {
                    i += 1;
                }
            }
            b'[' if !ended => {
                while i < b.len() && b[i] != b']' {
                    i += 1;
                }
            }
            b'-' if b.get(i + 1) == Some(&b'-') => {
                while i < b.len() && b[i] != b'\n' {
                    i += 1;
                }
            }
            b'/' if b.get(i + 1) == Some(&b'*') => {
                i += 2;
                while i + 1 < b.len() && !(b[i] == b'*' && b[i + 1] == b'/') {
                    i += 1;
                }
                i += 1;
            }
            b';' => ended = true,
            c if ended && !c.is_ascii_whitespace() => return true,
            _ => {}
        }
        i += 1;
    }
    false
}

/// Core of [`run_sql`] / [`run_readonly_sql`]: prepare, optionally require
/// a read-only statement, bind `params` by `$name`, collect rows as JSON.
fn run_sql_values(
    db: &SqliteDb,
    sql: &str,
    params: &[(&str, crate::store::Value)],
    require_readonly: bool,
) -> Result<serde_json::Value> {
    let mut st = db.0.prepare(sql).context("prepare SQL")?;
    if require_readonly && !st.readonly() {
        bail!("sql is read-only: this statement would modify the database");
    }
    for (k, v) in params {
        if let Some(i) = st.parameter_index(&format!("${k}"))? {
            st.raw_bind_parameter(i, super::to_sql(v))?;
        }
    }
    let cols: Vec<String> = st.column_names().iter().map(|c| (*c).to_string()).collect();
    // ponytail: list columns come back as JSON text; parse them only when
    // the statement builds JSON, so plain strings starting with `[` survive.
    let json_ok = sql.contains("json_group_array")
        || sql.contains("json_object")
        || sql.contains("json_array");
    let mut rows = Vec::new();
    let mut q = st.raw_query();
    while let Some(r) = q.next().context("run saved-query SQL")? {
        let mut obj = serde_json::Map::new();
        for (i, c) in cols.iter().enumerate() {
            let v = match r.get_ref(i)? {
                ValueRef::Null => serde_json::Value::Null,
                ValueRef::Integer(n) => n.into(),
                ValueRef::Real(f) => serde_json::Number::from_f64(f)
                    .map_or(serde_json::Value::Null, serde_json::Value::Number),
                ValueRef::Text(t) | ValueRef::Blob(t) => {
                    let s = String::from_utf8_lossy(t).into_owned();
                    let parsed = if json_ok && (s.starts_with('[') || s.starts_with('{')) {
                        serde_json::from_str(&s).ok()
                    } else {
                        None
                    };
                    parsed.unwrap_or(serde_json::Value::String(s))
                }
            };
            obj.insert(c.clone(), v);
        }
        rows.push(serde_json::Value::Object(obj));
    }
    Ok(serde_json::json!({"columns": cols, "row_count": rows.len(), "rows": rows}))
}

#[cfg(test)]
#[allow(clippy::unwrap_used, reason = "tests panic on broken invariants")]
mod tests {
    use super::*;
    use crate::store::query::saved::SAVED_QUERIES;

    #[test]
    fn second_statement_detection_ignores_literals_and_comments() {
        assert!(!has_second_statement("SELECT 1"));
        assert!(!has_second_statement("SELECT 1;"));
        assert!(!has_second_statement("SELECT 1; -- done\n /* x */ "));
        assert!(!has_second_statement("SELECT ';' , \"a;b\", `c;d`, [e;f]"));
        assert!(!has_second_statement("SELECT 1 -- ; DELETE FROM Doc"));
        assert!(has_second_statement("SELECT 1; DELETE FROM Doc"));
        assert!(has_second_statement("SELECT 1;\n\nSELECT 2"));
        assert!(has_second_statement("SELECT 1; /* c */ DROP TABLE Doc"));
    }

    #[test]
    fn readonly_sql_refuses_writes_and_binds_params() {
        let root = std::env::temp_dir().join(format!(
            "doc-linter-ro-sql-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&root).unwrap();
        crate::store_sqlite::build_and_swap(&root, |db| {
            db.execute_batch("INSERT INTO Doc(id, title) VALUES ('doc-a', 'Alpha'), ('b', 'Beta')")
        })
        .unwrap();
        // A read-write handle, so only the statement check stands between
        // the caller and a write.
        let db = crate::store_sqlite::open_rw(&root).unwrap();
        let v = crate::store::Value::Str;
        let ok = run_readonly_sql(
            &db,
            "-- all docs\nWITH d AS (SELECT id FROM Doc WHERE id REGEXP $re) SELECT count(*) AS n FROM d",
            &[("re", v("doc-.*".into())), ("unused", v("x".into()))],
        )
        .unwrap();
        assert_eq!(
            ok["rows"][0]["n"], 1,
            "REGEXP matches the whole string: {ok}"
        );
        let none = run_readonly_sql(&db, "SELECT id FROM Doc WHERE id REGEXP 'doc'", &[]).unwrap();
        assert_eq!(none["row_count"], 0, "{none}");
        assert!(
            run_readonly_sql(&db, "SELECT 'x' REGEXP '('", &[]).is_err(),
            "bad pattern errors"
        );
        for bad in [
            "DELETE FROM Doc",
            "WITH d AS (SELECT 1) DELETE FROM Doc",
            "SELECT 1; DELETE FROM Doc",
            "PRAGMA user_version = 3",
            "VACUUM",
            "",
        ] {
            assert!(
                run_readonly_sql(&db, bad, &[]).is_err(),
                "`{bad}` must be refused"
            );
        }
        let n = run_readonly_sql(&db, "SELECT count(*) AS n FROM Doc", &[]).unwrap();
        assert_eq!(n["rows"][0]["n"], 2, "nothing was deleted: {n}");
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn every_catalog_entry_has_embedded_sql() {
        for q in SAVED_QUERIES {
            assert!(builtin_sql(q.name).is_some(), "no SQL for {}", q.name);
        }
        assert_eq!(SAVED_SQL.len(), SAVED_QUERIES.len());
    }

    /// The six corpus-ratio queries used to return no rows on an empty set;
    /// each must now return exactly one row on an empty graph.
    #[test]
    fn corpus_ratio_queries_return_a_row_on_an_empty_graph() {
        let root = std::env::temp_dir().join(format!(
            "doc-linter-empty-ratio-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&root).unwrap();
        crate::store_sqlite::build_and_swap(&root, |_| Ok(())).unwrap();
        let db = crate::store_sqlite::open_rw(&root).unwrap();
        for name in [
            "corpus-purpose-classifier",
            "corpus-cold-start-summary",
            "unified-corpus-diagnostic",
            "corpus-entities-per-doc-ratio",
            "corpus-functions-per-file-ratio",
            "corpus-doc-coverage-ratio",
        ] {
            let out = run_saved_query_with_root(&db, None, name, &HashMap::new()).unwrap();
            assert_eq!(out["row_count"], 1, "{name}: {out}");
        }
        let _ = std::fs::remove_dir_all(&root);
    }
}
